#version: '3'
services:
  warp-container:
    container_name: warp-container
    image: ubuntu:latest
    restart: 'no'
    tty: true  #helps while troubleshooting; sudo docker exec -it [containerID] /bin/bash
    ports:
      - 9000:9000/tcp #make sure this matches values in init script
    sysctls:
#      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.conf.all.route_localnet=1
    volumes:
      - ./init.sh:/tmp/init.sh
#      - /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
    environment:
      - SERVERPORT=9000
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    command: bash -c "/tmp/init.sh && /bin/bash"